spring.application.name=TFG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
app.certificados.directorio=certificados
app.certificados.master-secret=${CERT_MASTER_SECRET}
app.admin.nombre=${ADMIN_NOMBRE:ADMIN}
app.admin.cif=${ADMIN_CIF:ADMIN}
app.admin.email=${ADMIN_EMAIL:admin@easyfactura.local}
app.admin.password=${ADMIN_PASSWORD:admin1234}
